name: Build Source Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-src:
    runs-on: ubuntu-latest
    name: Build Source Package

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check

      - name: Build source package
        run: |
          pkg_file <- pkgbuild::build()
          dir.create("build")
          file.copy(pkg_file, "build")
        shell: Rscript {0}

      - name: Upload source package
        uses: actions/upload-artifact@v4
        with:
          name: Pmetrics-source
          path: build/
          
      - name: Upload source to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/*.tar.gz
          asset_name: Pmetrics-source.tar.gz
          asset_content_type: application/gzip
